### ISSUE TITLE
刚从ubuntu 的snap推荐下载了，感觉功能还不是很多啊？有规划什么feauture list 吗

### ISSUE THREAD

**Issue by baiyutang** [Suremotoo/e-tools#12]

**Comment by Suremotoo** [comment]
**e-tools** 是我根据自己在工作中常用的一些小工具简单的整理，目前还没有明确以及完整的功能规划清单。后面用到什么功能，会往里面加，如果您有更好的建议和需要的功能，这边都可以尝试添加进去～，当然您也可以新增或修改后提交PR。
当时为了图快，是用比较熟悉的Jquery+LayUI写的（非常容易上手），仅用electron做跨平台打包。
我这边准备后续将使用 *Vue* 进行代码的重写以及调整！

**Comment by baiyutang** [comment]
可以啊，我也比较熟悉vue，到时候可以帮你写点
