### ISSUE TITLE
Package did not install in English

### ISSUE THREAD

**Issue by aaronxn** [Suremotoo/e-tools#19]
My system language is English, but the package didn't install in English.

See: https://i.imgur.com/NuOD6B9.png

**Comment by Suremotoo** [comment]
You can enter the English menu by clicking the upper right corner.

![image](https://user-images.githubusercontent.com/26423989/91639989-2b6a7580-ea4d-11ea-879d-906152cade96.png)
![image](https://user-images.githubusercontent.com/26423989/91640004-40df9f80-ea4d-11ea-88fd-8537520db13b.png)
