### ISSUE TITLE
Logo Proposal

### ISSUE THREAD

**Issue by radudangratian** [Suremotoo/e-tools#3]
Hello! I saw you actual logo. I am a PRO designer willing to help Open Source projects in my spare time. I would like to know if you are interested with a proposal for a new logo .

The logo will be modern and will follow the last trends.

Waiting for a response from you.

Regards, Radu Dan!

**Comment by Suremotoo** [comment]
I'd be very happy，if you’d like。

You can send your work to my mailbox.: suremotoo@163.com
